#name : try/catch
# --
try {
  $0
} catch ($1 e) {
  throw new RuntimeException(e);
}